### ISSUE TITLE
Why PartialOrd is needed?

### ISSUE THREAD

**Issue by pickfire** [teh-cmc/rust-async#3]
In https://github.com/teh-cmc/rust-async#11b-extensions:

> < Here we define a BoundsExt trait and provide a default implementation for everything that is an Iterator (provided that their Items are PartialOrd, of course!):

Can I know why is `PartialOrd` required?

**Comment by Lonami** [comment]
The `next` implementation uses comparison operators (`>=` and `<`) in **1.1.a. Combinators**. You can't use them unless it implements `PartialOrd`:
```rust
impl<I> Iterator for Bounds<I, I::Item>
where
    I: Iterator,
    I::Item: PartialOrd,
{
    type Item = I::Item;

    fn next(&mut self) -> Option<Self::Item> {
        loop {
            match self.inner.next() {
                Some(v) if v >= self.min && v < self.max => return v.into(),
                Some(_) => {}
                None => return None,
            }
        }
    }
}
```

**Comment by pickfire** [comment]
Oh, I just noticed that. But how come it was not mentioned in **1.1.a** but in **1.1.b**?

**Comment by teh-cmc** [comment]
> Can I know why is `PartialOrd` required?

C.f. @Lonami's answer.

> Oh, I just noticed that. But how come it was not mentioned in **1.1.a** but in **1.1.b**?

It is idiomatic in Rust to specify required trait bounds as granularly (i.e. "late") as possible, as it generally leads to better code reusability.

Section **1.1.a** declares `Bounds` like this:
```rust
pub struct Bounds<I, T> { /* ... */ }
impl<I, T> Bounds<I, T> { /* ... */ }
impl<I> Iterator for Bounds<I, I::Item>
where
    I: Iterator,
    I::Item: PartialOrd,
{ /* ... */ }
```
It is explicit from this code that `I::Item` needs to be `PartialOrd` for `Bounds` to implement `Iterator`.

OTOH, section **1.1.b** declares `BoundsExt` as such:
```rust
pub trait BoundsExt: Iterator
where
    Self: Sized,
{
    fn bounds<T>(self, min: T, max: T) -> Bounds<Self, T> {
        Bounds::new(self, min, max)
    }
}

impl<I: Iterator> BoundsExt for I {}
```
No `PartialOrd` trait bounds here: anything that is `Sized` and implements `Iterator` will be able to construct a `Bounds` combinator via `self.bounds(...)`.

Hence this comment that you quoted, which is meant to remind the reader that there are some trait bounds that aren't explicitly re-stated here that will still apply further down the chain.
> < Here we define a BoundsExt trait and provide a default implementation for everything that is an Iterator (provided that their Items are PartialOrd, of course!):

Code:
```rust
struct MyInt(i32);

let a = (0..3);
let b = (0..3).map(MyInt);

let mut a = a.bounds(0, 2); // works
let mut b = b.bounds(0, 2); // works

a.next(); // works
b.next(); // doesn't compile: "method `next` not found for this"
```
