### ISSUE TITLE
The first chapter was pretty good

### ISSUE THREAD

**Issue by MightyPork** [teh-cmc/rust-async#7]
Just wanted to say that; so you know it's appreciated, if you ever decide to continue ;)

**Comment by teh-cmc** [comment]
Thanks mate :) I sure hope I'll find back the free time and energy to do some more serious open source stuff at some point...

In any case, Philipp [covered this specific matter much better than I ever could](https://os.phil-opp.com/async-await/) anyway :)

Cheers :beers:
